server:
  port: 8081
#绑定远程仓库
spring:
  application:
    name: spring-cloud-config-server-8081
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Spark-shell/microservice-config.git