server:
  port: 7001
spring:
  application:
    name: SPRING-CLOUD-EUREKA-SERVER
# eureka配置
eureka:
  instance:
    hostname: 192.168.199.56
  client:
    service-url:
      defaultZone: http://192.168.199.56:7001/eureka/
    register-with-eureka: false                 #当前的eureka-server自己不注册进服务列表
    fetch-registry: false                       #不通过Eureka获取注册信息
