server:
  port: 7001
spring:
  application:
    name: SPRING-CLOUD-EUREKA-SERVER
# eureka配置
eureka:
  instance:
    hostname: eureka7001.com
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
    register-with-eureka: false   #当前的eureka-server自己不注册进服务列表
    fetch-registry: false         #不通过Eureka获取注册信息
