server:
  port: 8082
person:
    lastName: hello
    age: 18
    boss: false
    birth: 2017/12/12
    port: ${server.port}
file:
  path: 123456
  prefix: 123456
  fileType: 123456
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    encoding: UTF-8
    cache: false
    enabled: true
    mode: LEGACYHTML5
    prefix:
  devtools:
    restart:
      enabled: true
  profiles:
    active: defaut #指定要激活的配置
debug: true
logging:
#  file: logs/system.log     # 日志文件,相对路径,日志文件会建在当前项目根目录下，D:\WorkSpace\JavaWebEdit\springBootProjects\springboots\spring-boot-basic-practice\logs\system.log
  path: logs                 # 日志路径相对路径,日志文件会建在当前项目根目录下
  pattern:
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
    file: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
---
server:
  port: 8081
spring:
  profiles: prod
---
server:
  port: 8083
spring:
  profiles: dev