server:
  port: 8001
spring:
  application:
    name: SPRINGCLOUD-SESSION-REDIS-8001
  redis:
    host: 192.168.199.56
    port: 6379
#    password: 123456
    timeout: 6000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    database: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: springcloud-session-redis-8001
    prefer-ip-address: true   #访问路径显示Ip

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"